config/routes.rb
Comparendo::Application.routes.draw do




  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags
  end

  resources :contacts
  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
    end
  end

  # translated path

  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2(/:id)' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3(/:id)' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4(/:id)' => "company#eintragen4", :as => 'company_add4'
  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details

  get 'architekten/:region/:uid/:company' => "company#show"
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/models/article.rb
class Article < ActiveRecord::Base
  THUMB_SIZE = "200x150"
  SIZE_FOR_SHORT = 800

	attr_accessible :author, :title, :body, :tags, :images_attributes
  belongs_to  :author, :class_name => "User", :foreign_key => "author_id"
  
  has_many :images, :as => :imageable
  has_many :tags, :through => :taggings
  has_many :taggings, :as => :taggable

  validates :author, :presence => true
  validates :title, :presence => true, :length => { :maximum => 150 }


  before_save :set_path
  accepts_nested_attributes_for :images


  def has_cover_image?
    images.any? && !images.last.new_record?
  end

  def short_description
    body.size > SIZE_FOR_SHORT ? "#{body[0..SIZE_FOR_SHORT]}..." : body
  end

  def cover_image
    images.last.image
  end

  def thumb_image
    images.last.image.thumb(THUMB_SIZE)
  end


  def self.autocomplete_clickable(field, query_pattern, &block)
    articles = Article.order(field).where("#{field} LIKE ?", "%#{query_pattern}%")
    links = articles.map { |item| block.call(item) }
    values = articles.map { |item| "#{item.send(field)}" }
    JqueryAutocomplete.array_of_clickable values, links
  end


  def self.last_five
    Article.order("id desc").limit(5)
  end


private

  def set_path
    require 'code_extensions.rb'
    self.path = CodeExtensions::PARSE_FOR_PATH.(title.strip.downcase)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController
  set_tab :article
	before_filter :init_article, :only => [:edit, :update, :show, :destroy]
  add_breadcrumb "Informationen", "/infos"

  def index
		@articles = Article.order("id").page(params[:page])
	end

	def new
		@article = current_user.articles.new
		@article.images.build
    add_breadcrumb "#{t('article.create')}", ""
	end

	def create
		@article = current_user.articles.new params[:article]
		respond_to do |format|
			if @article.save
				format.html { redirect_to admin_article_path(@article)}
			else
				flash[:error] = @article.errors.full_messages.join(", ")
				format.html { render :new }
			end
		end
	end

	def show
	end

	def edit
		@article.images.build unless @article.has_cover_image?
    add_breadcrumb "#{@article.title}", "/infos/#{@article.path}"
    add_breadcrumb "#{t('article.edit')}", ""
	end

	def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
      		format.html {redirect_to admin_article_path(@article)}
         format.json  { render :json => @article }
      else
        format.json  { render :json => @article.errors }
      end
    end
	end

	def destroy
		@article.destroy
		respond_to do |format|
			format.html { redirect_to admin_articles_path }
		end
	end

	def tags
		@articles = Article.order("id")
		@tags = @articles.map(&:tags).join(",").split(",").uniq
		@tags.map!{|t| t if t.include?(params[:term])}.compact! unless params[:term].blank?
		respond_to do |format|
      format.json { render :json => @tags.map{|t| {:id => t, :label => t, :value => t }} }
    end
	end

	private
		def init_article
			@article = Article.find_by_id params[:id]
			redirect_to admin_articles_path if @article.nil?
		end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  set_tab :article
 	add_breadcrumb "Informationen", "/infos"
  before_filter :newest_infos, :only => [:overview, :show]
  
	def overview
    @articles = Article.order("id").page(params[:page])
	end

  def show
    @article = Article.find_by_path(params[:path])
    redirect_to :action => :overview if @article.nil?
    add_breadcrumb "#{@article.title}", ""
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, '#', :class => "add_fields", 
          :data => {:id => id, :fields => fields.gsub("\n", "")})
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/admin/articles/_article.html.erb
 <% content_for :head do %>
     <%= javascript_include_tag "jquery.jeditable.mini" %>
     <%= javascript_include_tag "article" %>
<%end%>
<h2 class="editable_text" id="article_title"><%=article.title %></h2>
<p>
    <% if article.has_cover_image? %>
        <%= action == :index ? image_tag(article.thumb_image.url) : image_tag(article.cover_image.url) %>
    <% end %>
    <%= action == :index ? raw(article.short_description) : raw(article.body) %>
</p>
<div><%= t('article.author') %>:
    <%= link_to article.author.name, nil %>
</div>
<% unless article.tags.blank? %>
    <div>Tags:
    	<% tags = [] %>
        <% article.tags.split(",").each do |tag| %>
            <% tags << link_to(tag, nil) %>
        <% end %>
        <%= tags.join(", ").html_safe %>
    </div>
<% end %>
<% if can? :update, article %>
    <%= link_to "Edit", edit_admin_article_path(article) %>
<% end %>
<% if can? :destroy, article %>
    <%= form_for([:admin, article], :method => 'delete') do |f| %>
        <%= f.submit('delete') %>
    <% end %>
<% end %>

app/views/admin/articles/_form.html.erb
<% content_for :head do %>
    <script type="text/javascript">
        $(function() {
            $('.tags').tagsInput({
                autocomplete_url: "/admin/articles/tags",
                interactive: true
            });
        });
    </script>
<% end %>


<%= form_for(@article, :url => {:action => action}, :html => {:multipart => true} ) do |f| %>
    <table>
        <tr>
            <td><%= f.label(:title) %></td>
            <td><%= f.text_field(:title) %></td>
        </tr>
        <tr>
            <td><%= f.label(:body) %></td>
            <td><%= f.text_area(:body, {:rows => 5, :class => "ckeditor"}) %></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td><%= image_tag @article.cover_image.url if @article.has_cover_image? %></td>
        </tr>
        <tr>
            <%= f.fields_for :images do |builder| %>
                <td><%= builder.label :image, "Image" %></td>
                <td><%= builder.file_field :image %></td>
            <% end %>
        </tr>
        <tr>
            <td><label>Tags</label></td>
            <td><%= f.text_field(:tags, {:class => 'tags'}) %></td>
        </tr>
        
        <tr>
            <td>
                <%= f.submit('submit') %>
            </td>
        </tr>
    </table>
<% end %>

app/views/admin/articles/edit.html.erb
<h2>Edit Article</h2>

<%= render :partial => 'form', :locals => {:action => :update} %>

app/views/admin/articles/index.html.erb
<h1>Articles</h1>
<% if can? :create, Article %>
    <%= link_to t('article.create'), new_admin_article_path %>
<% end %>

<section>
	<% @articles.each do |article| %>
	    <article>
	        <%= render "article", {:action => :index, :article => article } %>
	    </article>
	<% end %>
</section>
<%= paginate @articles %>

app/views/admin/articles/new.html.erb
<h2>New Article</h2>

<%= render :partial => 'form', :locals => {:action => :create} %>

app/views/admin/articles/show.html.erb
<div>
    <%= render "article", {:action => :show, :article => @article } %>
</div>