config/routes.rb
Comparendo::Application.routes.draw do




  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags
  end

  resources :contacts
  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
    end
  end

  # translated path

  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2(/:id)' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3(/:id)' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4(/:id)' => "company#eintragen4", :as => 'company_add4'
  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details

  get 'architekten/:region/:uid/:company' => "company#show"
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/controllers/offer_controller.rb
class OfferController < ApplicationController
  set_tab :offer
  add_breadcrumb "Offerte anfordern", '/offerte-anfordern'
  before_filter :newest_infos, :only => :new

  def new

    if params[:category_id].nil?
      @categories = Category.all
      @row_in_column = @categories.count / 2
      @categories.each {|cat| @row_in_column += cat.subcategories.count}
      @row_in_column = @row_in_column / 3
      render 'select_category'
    else
      @category = Category.find(params[:category_id])
      unless @category
        @category = Category.new
      #else
      #  flash[:error] = t('offer.notices.project_type_not_found')
      #  redirect_to new_offer_url
      end
    end
  end

  def create
    #unless current_user
    #  session[:project] = params[:project]
    #  session[:user_return_to] = offer_created_url
    #  flash[:error] = t(:you_need_to_login_to_continue)
    #  redirect_to new_user_session_url
    #  return
    #end

    #project = params[:project]
    #
    #project[:start_date] = Date.new(project[:start_date_year].to_i, project[:start_date_month].to_i, 1)
    #project[:end_date] = Date.new(project[:end_date_year].to_i, project[:end_date_month].to_i, 1)
    #project[:data][:land_available] = (project[:data][:land_available] == '1') ? true : false
    #
    #@project = current_user.projects.create(project.except(:start_date_month, :start_date_year, :end_date_month, :end_date_year))
    #if @project
    #  redirect_to offer_created_url
    #else
    #  flash[:error] = @project.errors.full_messages[0]
    #  render :new
    #end
  end

  def created
    #if session[:project].present?
    #  project = session[:project]
    #  session[:project] = nil
    #
    #  project[:start_date] = Date.new(project[:start_date_year].to_i, project[:start_date_month].to_i, 1)
    #  project[:end_date] = Date.new(project[:end_date_year].to_i, project[:end_date_month].to_i, 1)
    #  project[:data][:land_available] = (project[:data][:land_available] == '1') ? true : false
    #
    #  @project = current_user.projects.create(project.except(:start_date_month, :start_date_year, :end_date_month, :end_date_year))
    #  if @project
    #    # render :created
    #  else
    #    flash[:error] = @project.errors.full_messages[0]
    #    render :new
    #  end
    #else
    #  # render :created
    #end
  end

  def show
    # TODO
  end

end

app/helpers/offer_helper.rb
module OfferHelper
end

app/views/offer/created.html.erb
<div class="column leftcolumn">
  <h1><%= t('.title') %></h1>

  <p><%= t('.text') %></p>
</div>

app/views/offer/new.html.erb
<div id="main-left-wrapper">
  <h2><%= t('.your_project') %></h2>
  <%= form_for @project, :url => offer_index_url, :method => :post,
               :html => {:id => 'new_offer_form'} do |f| %>
    <input type="hidden" name="project[project_type_id]" value="<%= @project.project_type.id %>" />

    <h2><%= t('.select_the_details_of_the_project') %></h2>

    <!-- land available -->
    <div class="clearfix">
      <label class="form-label"><%= t('.land_available') %></label>
      <div id="project_data_land_available_buttons" class="btn-group" data-toggle="buttons-radio">
        <button type="button" class="btn active" value="1"><%= t('.button_yes') %></button>
        <button type="button" class="btn" value="0"><%= t('.button_no') %></button>
      </div>
      <input type="hidden" id="project_data_land_available" name="project[data][land_available]" value="1" />
      <br />
      <script type="text/javascript">
        $('#project_data_land_available_buttons button').click(function (event) {
          $('#project_data_land_available').attr('value', $(this).attr('value'));
        });
      </script>
    </div>

    <!-- size in square meters -->
    <div class="clearfix">
      <label class="form-label"><%= t('.size_in_square_meters') %></label>
      <div class="slider-container">
        <input type="slider" id="project_data_size" name="project[data][size]" value="100" />
        <script type="text/javascript">
          $('#project_data_size').slider({
            from: 10,
            to: 10000,
            step: 10,
            round: 10,
            smooth: false,
            heterogeneity: ["25/200", "50/1000", "75/5000"],
            scale: [10, 200, 1000, 5000, 10000],
            skin: "round"
          })
        </script>
      </div>
    </div>

    <!-- number of floors -->
    <div class="clearfix">
      <label class="form-label"><%= t('.number_of_floors') %></label>
      <div class="slider-container">
        <input type="slider" id="project_data_floors" name="project[data][floors]" value="1" />
        <script type="text/javascript">
          $('#project_data_floors').slider({
            from: 1,
            to: 10,
            step: 1,
            round: 1,
            smooth: false,
            skin: "round"
          })
        </script>
      </div>
    </div>

    <!-- number of rooms -->
    <div class="clearfix">
      <label class="form-label"><%= t('.number_of_rooms') %></label>
      <div class="slider-container">
        <input type="slider" id="project_data_rooms" name="project[data][rooms]" value="2" />
        <script type="text/javascript">
          $('#project_data_rooms').slider({
            from: 1,
            to: 20,
            step: 1,
            round: 1,
            smooth: false,
            skin: "round"
          })
        </script>
      </div>
    </div>

    <!-- number of bath rooms -->
    <div class="clearfix">
      <label class="form-label"><%= t('.number_of_bathrooms') %></label>
      <div class="slider-container">
        <input type="slider" id="project_data_bathrooms" name="project[data][bathrooms]" value="1" />
        <script type="text/javascript">
          $('#project_data_bathrooms').slider({
            from: 1,
            to: 10,
            step: 1,
            round: 1,
            smooth: false,
            skin: "round"
          })
        </script>
      </div>
    </div>

    <hr />

    <h2><%= t('.completing_project') %></h2>

    <div class="clearfix">
      <label class="form-label"><%= t('.what_is_your_estimated_budget') %></label>
      <div class="control-group">
        <%= f.text_field :budget %> CHF
      </div>
    </div>

    <div class="clearfix">
      <label class="form-label"><%= t('.period_in_which_they_want_to_build') %></label>
      <label class="form-label"><%= t('.label_start') %></label>
      <div class="control-group">
        <select id="project_start_date_month" name="project[start_date_month]">
          <% 1.upto(12) do |month| %>
            <option value="<%= month %>"><%= t('date.month_names')[month]%></option>
          <% end %>
        </select>
        <select id="project_start_date_year" name="project[start_date_year]">
          <option value="2012">2012</option>
          <option value="2013">2013</option>
          <option value="2014">2014</option>
          <option value="2015">2015</option>
          <option value="2016">2016</option>
        </select>
      </div>
      <label class="form-label"><%= t('.label_end') %></label>
      <div class="control-group">
        <select id="project_end_date_month" name="project[end_date_month]">
          <% 1.upto(12) do |month| %>
            <option value="<%= month %>"><%= t('date.month_names')[month]%></option>
          <% end %>
        </select>
        <select id="project_end_date_year" name="project[end_date_year]">
          <option value="2012">2012</option>
          <option value="2013">2013</option>
          <option value="2014">2014</option>
          <option value="2015">2015</option>
          <option value="2016">2016</option>
        </select>
      </div>
    </div>

    <%= f.submit t('.button_submit'), :class => 'btn' %>
  <% end %>
</div>

<div id="main-right-wrapper">
  <h3><%= t('.what_to_consider') %></h3>
</div>
<div class="clr"></div>

app/views/offer/select_category.html.erb
<div id="main-left-wrapper">
  <h2><%= t('.sweden_architect_applications') %></h2>
  <p><%= t('.choose_your_category') %></p>
  <% count = 0 %>
  <div id="project_type_container" class="clearfix">
    <div class="category_column">
    <% @categories.each do |cat| %>
            <%count += cat.subcategories.count%>
            <% if count  >= @row_in_column + 1 %>
              </div>
              <div class="category_column">
              <% count = 0 %>
            <% else %>
              <% count.next %>
            <% end %>
      <div class="project_type">
        <div class="hover-title clearfix">
          <a href="<%= new_offer_path(:category_id => cat.id) %>"><%= cat.name %></a>
        </div>
        <% if cat.icon.present? %>
          <a href="<%= new_offer_path(:category_id => cat.id) %>">
            <%= image_tag "project_type/#{cat.icon}" %>
          </a>
        <% end %>
        <% cat.subcategories.each do |subcat| %>
            <div class="subcategory_type">
              <div class="hover-title clearfix">
                <%= form_tag(quote_details_path) do %>
                  <%= hidden_field_tag "subcategory_id", subcat.id %>
                  <%= submit_tag subcat.name %>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>

  <!--
  <div class="clearfix" style="float: right;">
    <a href="#" class="button"><%= t('.forward') %></a>
  </div>
  -->
</div>

<div id="main-right-wrapper">
  <h3><%= t(:how_does_it_work) %></h3>
  <ul>
    <li class="one-bul"><a href="#">Kurzes Formular</a></li>
    <li class="two-bul"><a href="#">Abschicken</a></li>
    <li class="three-bul"><a href="#">3 Offerten erhalten</a></li>
  </ul>

  <div class="clr"><br><br><br></div>

  <%= render "layouts/latest_news"%>

  <div class="clr"><br><br><br></div>

  <h3>Top-Anbieter:</h3>
  <ul>
    <li><a href="#">Geprüft durch uns</a></li>
    <li><a href="#">Hintergrund-Check</a></li>
    <li><a href="#">Interview</a></li>
  </ul>

</div>
<div class="clr"></div>