config/routes.rb
Comparendo::Application.routes.draw do




  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags
  end

  resources :contacts
  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
    end
  end

  # translated path

  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2(/:id)' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3(/:id)' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4(/:id)' => "company#eintragen4", :as => 'company_add4'
  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details

  get 'architekten/:region/:uid/:company' => "company#show"
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/controllers/admin/company_controller.rb
class Admin::CompanyController < Admin::AdminController

  before_filter :load_cities, :only => [:new, :edit, :create, :update]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    respond_to do |format|
      if @company.save
        format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully created.' }
      else
        flash[:error] = @company.errors.values[0][0]
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully updated.' }
      else
        flash[:error] = @company.errors.values[0][0]
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully deleted.' }
    end
  end

  private

    def load_cities
      @cities = City.all
    end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  
  set_tab :company, :only => %w(eintragen eintragen1 eintragen2 eintragen3 eintragen4)
  set_tab :home, :only => %w(index show edit update)
  
  before_filter :newest_infos, :only => [:index, :eintragen]
  before_filter :load_cities, :only => [:edit, :update]
  before_filter :authenticate_user!, :except=>[:index, :show, :eintragen]

  load_and_authorize_resource
  add_breadcrumb I18n.t('architect'), :architekten_path
  

  def index
    add_breadcrumb I18n.t('architect'), "#{url_for(:only_path => true)}/?#{request.query_string}"
    @companies = Company.search_by_query(params)
    @title = search_page_titles
    append_page_title @title
    append_meta_tags_search_page
  end



  def show
    if params[:id].present?
      @company = Company.find_by_id(params[:id])

    elsif params[:region].present? and params[:uid] and params[:company].present?
      @company = Company.find_by_uid(params[:uid])

    elsif params[:region].present? and params[:city].present? and params[:company].present?
      #will always throw an exception! Must be fixed or route must be removed
      @company = Company.where("name like ?","%#{params[:company]}%")

    else
      render_404
    end

    unless @company
      render_404
      return
    end

    add_breadcrumb_to_show_page
  end


  def edit
    @company = Company.find(params[:id])
    @regions = switzerland_regions
  end


  def update
    @company = Company.find(params[:id])

    # get city
    @city = City.where("lower(name) = ? AND region_id = ?", params[:company][:city].downcase,
                       params[:company][:region_id]).first
    if @city.nil?
      @region = Region.find(params[:company][:region_id])
      @city = @region.cities.create(:name => params[:company][:city])
    end
    params[:company][:city_id] = @city.id

    respond_to do |format|
      if @company.update_attributes(params[:company].except(:city))
        format.html { redirect_to company_url(@company), :notice => 'Company was successfully updated.' }
        format.json { render :json => {:success => true} }
      else
        format.html {
          flash[:error] = @company.errors.values[0][0]
          render :action => "edit"
        }
        format.json { render :json => {:success => false, :message => @company.errors.values[0][0]} }
      end
    end
  end

  def update_cover_image
    authorize! :update, Company
    authorize! :create, Image

    @company = Company.find(params[:id])
    size = params[:size] || '200x140'
    if @company.update_attributes(params[:company])
      render :json => {
        :success => true,
        :image => {
          :name => @company.cover_image_name,
          :url => @company.cover_image.thumb(size).url,
          :delete_url => image_url(@company.cover_image)
        }
      }
    else
      render :json => {:success => false, :message => @company.errors.values[0][0]}
    end
  end


  def eintragen
    if request.get?
      find_or_restore_company_step1
      
      if user_signed_in? && current_user.has_company?
        flash[:error] = "User cannot have multiple Companies" # TODO fix message and move to de.yml
        render "warning"
      end
    elsif request.post?
      add_company_step1

      unless user_signed_in?
        redirect_to new_user_session_url
        return
      end
    end

    @regions =  switzerland_regions
    add_breadcrumb "Firma eintragen", "firma-eintragen"
  end
  
  def eintragen2
    @company = Company.find(params[:id])
    authorize! :update, @company

    if params[:company]
      # get city
      @city = City.where("lower(name) = ? AND region_id = ?", params[:company][:city].downcase, params[:company][:region_id]).first
      if @city.nil?
        @region = Region.find_by_id(params[:company][:region_id])
        @city = @region.cities.create(:name => params[:company][:city]) if @region
      end
      params[:company][:city_id] = @city.id if @city

      if @company.update_attributes(params[:company].except(:city))
        redirect_to company_add3_url(:id => @company.id)
      else
        flash[:error] = @company.errors.values[0][0]
      end
    end

	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 2", "firma-eintragen/schritt-2"
  end
  
  def eintragen3
    @company = Company.find(params[:id])
    authorize! :update, @company

    if params[:company]
      specialties = prepare_specialties(params[:company].delete(:specialties))
      subcategories = prepare_subcategories params[:company].delete(:subcategories)

      if @company.update_attributes(params[:company])
        @company.tags << specialties
        @company.subcategories << subcategories
        @company.save
        redirect_to company_add4_url(:id => @company.id)
      else
        flash[:error] = @company.errors.values[0][0]
      end
    end

	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 3", "firma-eintragen/schritt-3"
  end

  def eintragen4
	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 4", "firma-eintragen/schritt-4"
  end

  private

################ adding company - step 1 ##################################

  def find_or_restore_company_step1
    @company =  if params[:id].present?
                  Company.find(params[:id])
                else
                  Company.new(temp_company)
                end
  end

  def add_company_step1
    unless user_signed_in?
      save_temp_data_to_login
      return
    end

    temp_company_clear
    @company =  params[:id].present? ? Company.find(params[:id]) : Company.new
    company_params = params[:company]
    company_params[:user_id] = current_user.id
    if @company.update_attributes(company_params)
      redirect_to company_add2_url(:id => @company.id)
    else
      flash[:error] = @company.errors.values[0][0]
    end
  end

  def save_temp_data_to_login
      self.temp_company = params[:company]
      session[:user_return_to] = request.url
      flash[:error] = t(:you_need_to_login_to_continue)
  end

  def temp_company
    session[:company] if session[:company].present?
  end

  def temp_company=(value)
    session[:company] = value
  end

  def temp_company_clear
    session[:company] = nil
  end

################ adding company - step 1 end ##################################




  def load_cities
      @cities = City.all
  end



  def add_breadcrumb_to_show_page
    add_breadcrumb_by_region_and_city @company.region_name, @company.city_name
    add_breadcrumb @company.name, nil
  end

  def add_breadcrumb_by_region_and_city(region_name=nil, city_name=nil)
    if region_name.nil? and city_name.nil?
      raise ArgumentError 'region_name and city_name are nil!'
    end

    search_options = {:utf8 => "%E2%9C%93", :q=>"architekten"}
    if region_name
      search_options[:region] = region_name
      add_breadcrumb "Architekten #{region_name}",generate_search_query(search_options)
    end

    if city_name
      search_options[:city] = city_name
      add_breadcrumb "Architekten #{city_name}",generate_search_query(search_options)
    end
  end


  def generate_search_query(search_options)
    "/company?#{CGI.unescape(search_options.to_query)}"
  end

  def switzerland_regions
    Country.find_by_name('Switzerland').regions
  end


  def search_page_titles
    title = I18n.t('company.index.title')
    tag = params[:tag]
    city = params[:city]
    region = params[:region]

    if tag.present?  or city.present? or region.present?

      if city.present?
        title << " #{city}"
        title << ", " if region.present?
      end

      title << " #{region}" if region.present?
      title << " - #{tag}" if tag.present?
    else
      title << " #{I18n.t('switzerland')}"
    end

    title
  end

  def append_meta_tags_search_page
    append_meta_keywords_search_page
    append_meta_tag_description "A description of Company -> Architekten search page"
  end

  def append_meta_keywords_search_page
    fields = params.values_at(:tag, :city, :region).select(&:present?)
    append_meta_tag_keywords(fields.join(", ").concat(".")) unless fields.empty?
  end

  def prepare_specialties str_specialties
    current_specialties = @company.tags
    new_specialties = []
    for_destroy = []
    for_create = []

    unless str_specialties.blank?
      str_specialties.split(",").uniq.each do |name|
        new_specialties << Tag.find_or_create_by_name(name: name)
      end
      new_specialties.uniq! unless new_specialties.empty?
    end

    for_destroy = current_specialties - new_specialties
    for_create = new_specialties - current_specialties

    for_destroy.each do |s|
      scp = Tagging.of_tag(s)
      scp = scp.of_taggable(@company)
      scp.destroy_all
    end
    for_create
  end

  def prepare_subcategories str_subcategories
    current_subcategories = @company.subcategories
    new_subcategories = []
    for_destroy = []
    for_create = []
    unless str_subcategories.blank?
      str_subcategories.split(",").uniq.each do |name|
        new_subcategories << Subcategory.find_by_name(name)
      end
      unless new_subcategories.empty?
        new_subcategories.uniq!
        new_subcategories.compact!
      end
    end
    for_destroy = current_subcategories - new_subcategories
    for_create = new_subcategories - current_subcategories

    for_destroy.each do |s|
      scp = CompanySubcategory.where(subcategory_id: s)
      scp = scp.where(company_id: @company)
      scp.destroy_all
    end
    for_create
  end
end

app/helpers/company_helper.rb
module CompanyHelper
  def company_city_name_or_default(company)
      company.city.present?  ? company.city.name : "(undefined city)"
  end

  def google_points_as_json
   points = Company.sponsors.map { |sponsor| {:latitude => sponsor.latitude, :longitude => sponsor.longitude, :name => sponsor.name, :city_name=> sponsor.city_name, :url=>url_to_company(sponsor) } }
    @companies.each do |company|
     if company.latitude and company.longitude
          points << {:latitude => company.latitude, :longitude => company.longitude, :name => company.name, :city_name=> company.city_name, :url=>url_to_company(company)}
     end
    end
   points = points.to_json if points
   points
  end
end

app/views/admin/company/_form.html.erb
<!--
TODO:
- handle multiple phone numbers
- handle multiple websites
- might want to set thumbnail arbitrarily
-->

<% content_for :head do %>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.tags').tagsInput();

            $('#add-image').live('change', function() {
                $("#new_image").ajaxSubmit({
                    success: function (data) {
                        if (data['success']) {
                            window.location = '<%= request.fullpath %>';
                        }
                    }
                });
            });

            $('.edit_image').submit(function(event) {
                event.preventDefault();
                $(this).ajaxSubmit({
                    success: function (data) {
                        if (data['success']) {
                            window.location = '<%= request.fullpath %>';
                        }
                    }
                });
            })
        });
    </script>
<% end %>

<div class="left-panel">
    <% if @company.id %>
        <%= link_to 'Show company page', url_for(@company) %>
    <% end %>

    <%= form_for(@company, :url => {:action => action}) do |f| %>
        <table>
            <tr>
                <td><label>City</label></td>
                <td>
                    <select id="company_city_id" name="company[city_id]">
                        <% @cities.each do |city| %>
                            <option value="<%= city.id %>"><%= city.name %></option>
                        <% end %>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label>Name</label></td>
                <td><%= f.text_field(:name) %></td>
            </tr>
            <tr>
                <td><label>Cover Image</label></td>
                <td>
                    <%= image_tag @company.cover_image.thumb('100x100').url if @company.cover_image_uid %>
                    <br />
                    <%= f.file_field :cover_image %>
                </td>
            </tr>
            <tr>
                <td><label>Email</label></td>
                <td><%= f.text_field(:email) %></td>
            </tr>
            <tr>
                <td><label>Address</label></td>
                <td><%= f.text_area(:address, {:rows => 5}) %></td>
            </tr>
            <tr>
                <td><label>Phone Numbers</label></td>
                <td>
                    <% unless @company.phone_numbers.nil? %>
                        <% @company.phone_numbers.each do |phone_number| %>
                            <input class="company_phone_number" name="company[phone_numbers][]" type="text" value="<%= phone_number %>" /><br />
                        <% end %>
                    <% end %>

                    <% if @company.phone_numbers.nil? or @company.phone_numbers.length == 0  %>
                        <input class="company_phone_number" name="company[phone_numbers][]" type="text" value="" /><br />
                    <% end %>
                </td>
            </tr>
            <tr>
                <td><label>Websites</label></td>
                <td>
                    <% unless @company.websites.nil? %>
                        <% @company.websites.each do |website| %>
                            <input class="company_website" name="company[websites][]" type="text" value="<%= website %>" /><br />
                        <% end %>
                    <% end %>

                    <% if @company.websites.nil? or @company.websites.length == 0 %>
                        <input class="company_website" name="company[websites][]" type="text" /><br />
                    <% end %>
                </td>
            </tr>
            <tr>
                <td><label>Description</label></td>
                <td><%= f.text_area(:description, {:rows => 5, :class => "ckeditor"}) %></td>
            </tr>
            <tr>
                <td><label>Additional Info</label></td>
                <td><%= f.text_area(:additional_info, {:rows => 5}) %></td>
            </tr>
            <tr>
                <td><label>Specialties</label></td>
                <td><%= f.text_field(:specialties, {:class => 'tags'}) %></td>
            </tr>
            <tr>
                <td />
                <td>
                    <%= f.submit('submit') %>
                </td>
            </tr>
        </table>
    <% end %>
</div>

<% if @company.id %>
    <div class="right-panel">
        <div class="side-bar">
            <div class="title">Images</div>
            <div id="company-images">
                <% @company.images.each do |image| %>
                    <div style="display: inline-block;">
                        <%= image_tag image.image.thumb('100x100').url if image.image_uid %>
                        <%= form_for [@company, image], {:method => :delete} do |f| %>
                            <%= f.submit 'delete' %>
                        <% end %>
                    </div>
                <% end %>
            </div>
            <br />

            <%= form_for [@company, Image.new], :html => {:multipart => true} do |f| %>
                Add Image <%= f.file_field :image, :id => 'add-image' %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/admin/company/edit.html.erb
<h2>Edit Company</h2>

<%= render :partial => 'admin/company/form', :locals => {:action => :update} %>

app/views/admin/company/index.html.erb
<h2>Companies</h2>

<%= link_to('New Company', new_admin_company_url) %>

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>City</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <% @companies.each do |company| %>
        <tr>
            <td><%= company.name %></td>
            <td><%= company.email %></td>
            <td><%= company.city.name %></td>
            <td><%= company.created_at %></td>
            <td><%= company.updated_at %></td>
            <td>
                <%= link_to('edit', edit_admin_company_url(company)) %>
            </td>
            <td>
                <%= form_for([:admin, company], :method => 'delete') do |f| %>
                    <%= f.submit('delete') %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>

app/views/admin/company/new.html.erb
<h2>New Company</h2>

<%= render :partial => 'admin/company/form', :locals => {:action => :create} %>