config/routes.rb
Comparendo::Application.routes.draw do




  devise_for :users, :controllers => {:sessions => 'sessions',:omniauth_callbacks => "users/omniauth_callbacks"  }

  namespace :admin do
    resources :company, :except => [:show]
    resources :articles
    resources :tags
  end

  resources :contacts
  resources :company, :only => [:index, :show, :edit, :update] do
    put :update_cover_image, :on => :member
    collection do
      get :company_names
    end

    resources :images, :only => [:index, :create]
    resources :reviews, :only => [:create, :destroy]
  end

  resources :subcategories, :only => [:index]

  resources :images, :only => [:destroy]
  resources :reviews, :only => [:create, :destroy]
  resources :cities, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :regions, :only => [] do
    get :name_autocomplete, :on => :collection
  end
  resources :offer, :only => [:new, :create, :show]

  resources :users, :only => [] do
    collection do
      get :check_email
      get :profil
      put :profil
    end
  end

  # translated path

  match '/infos' => "article#overview"
  match '/infos/:path' => "article#show"
  match '/kontakt' => "contacts#new"
  match '/kontaktmail' => "contacts#create"
  match '/infos' => "devise/article#overview"

  match '/offerte-angefordert' => "offer#created", :as => 'offer_created'
  match '/offerte-anfordern(/:project_type_id)' => "offer#new", :as => 'new_offer'
  match '/offerte/:id' => "offer#show"

  match 'firma-eintragen/schritt-2(/:id)' => "company#eintragen2", :as => 'company_add2'
  match 'firma-eintragen/schritt-3(/:id)' => "company#eintragen3", :as => 'company_add3'
  match 'firma-eintragen/schritt-4(/:id)' => "company#eintragen4", :as => 'company_add4'
  match 'firma-eintragen/abgeschlossen' => "company#finish", :as => 'company_add_finish'
  match 'firma-eintragen/abrechnung' => "company#payment", :as => 'company_payment'
  match 'firma-eintragen(/:id)' => "company#eintragen", :as => 'company_add'
  match 'architekten' => "company#index"

  post '/region-select' => "search#region_select", :as => :region_select
  post '/search' => "search#index", :as => :search
  post '/quote-details' => "quotes#new", :as => :quote_details
  post '/create-quote-details' => "quotes#create", :as => :create_quote_details

  get 'architekten/:region/:uid/:company' => "company#show"
  get '/:region/:city/:company' => "company#show"

  get '/about' => "footer#about"
  get '/jobs' => "footer#jobs"
  get '/privacy' => "footer#privacy"
  get '/terms' => "footer#terms"
  get '/sitemap' => "footer#sitemap"
  get '/impressum' => "footer#impressum"

  get "autocomplete/company_tag_article"
  get "autocomplete/company_tag"
  get "autocomplete/company_specialties"
  get "autocomplete/region_city"
  get "autocomplete/category_subcategory"
  root :to => 'home#index'

  match '*a', :to => 'errors#routing'
end

app/controllers/admin/company_controller.rb
class Admin::CompanyController < Admin::AdminController

  before_filter :load_cities, :only => [:new, :edit, :create, :update]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    respond_to do |format|
      if @company.save
        format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully created.' }
      else
        flash[:error] = @company.errors.values[0][0]
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully updated.' }
      else
        flash[:error] = @company.errors.values[0][0]
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to admin_company_index_url, :notice => 'Company was successfully deleted.' }
    end
  end

  private

    def load_cities
      @cities = City.all
    end

end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  
  set_tab :company, :only => %w(eintragen eintragen1 eintragen2 eintragen3 eintragen4)
  set_tab :home, :only => %w(index show edit update)
  
  before_filter :newest_infos, :only => [:index, :eintragen]
  before_filter :load_cities, :only => [:edit, :update]
  before_filter :authenticate_user!, :except=>[:index, :show, :eintragen]

  load_and_authorize_resource
  add_breadcrumb I18n.t('architect'), :architekten_path
  

  def index
    add_breadcrumb I18n.t('architect'), "#{url_for(:only_path => true)}/?#{request.query_string}"
    @companies = Company.search_by_query(params)
    @title = search_page_titles
    append_page_title @title
    append_meta_tags_search_page
  end



  def show
    if params[:id].present?
      @company = Company.find_by_id(params[:id])

    elsif params[:region].present? and params[:uid] and params[:company].present?
      @company = Company.find_by_uid(params[:uid])

    elsif params[:region].present? and params[:city].present? and params[:company].present?
      #will always throw an exception! Must be fixed or route must be removed
      @company = Company.where("name like ?","%#{params[:company]}%")

    else
      render_404
    end

    unless @company
      render_404
      return
    end

    add_breadcrumb_to_show_page
  end


  def edit
    @company = Company.find(params[:id])
    @regions = switzerland_regions
  end


  def update
    @company = Company.find(params[:id])

    # get city
    @city = City.where("lower(name) = ? AND region_id = ?", params[:company][:city].downcase,
                       params[:company][:region_id]).first
    if @city.nil?
      @region = Region.find(params[:company][:region_id])
      @city = @region.cities.create(:name => params[:company][:city])
    end
    params[:company][:city_id] = @city.id

    respond_to do |format|
      if @company.update_attributes(params[:company].except(:city))
        format.html { redirect_to company_url(@company), :notice => 'Company was successfully updated.' }
        format.json { render :json => {:success => true} }
      else
        format.html {
          flash[:error] = @company.errors.values[0][0]
          render :action => "edit"
        }
        format.json { render :json => {:success => false, :message => @company.errors.values[0][0]} }
      end
    end
  end

  def update_cover_image
    authorize! :update, Company
    authorize! :create, Image

    @company = Company.find(params[:id])
    size = params[:size] || '200x140'
    if @company.update_attributes(params[:company])
      render :json => {
        :success => true,
        :image => {
          :name => @company.cover_image_name,
          :url => @company.cover_image.thumb(size).url,
          :delete_url => image_url(@company.cover_image)
        }
      }
    else
      render :json => {:success => false, :message => @company.errors.values[0][0]}
    end
  end


  def eintragen
    if request.get?
      find_or_restore_company_step1
      
      if user_signed_in? && current_user.has_company?
        flash[:error] = "User cannot have multiple Companies" # TODO fix message and move to de.yml
        render "warning"
      end
    elsif request.post?
      add_company_step1

      unless user_signed_in?
        redirect_to new_user_session_url
        return
      end
    end

    @regions =  switzerland_regions
    add_breadcrumb "Firma eintragen", "firma-eintragen"
  end
  
  def eintragen2
    @company = Company.find(params[:id])
    authorize! :update, @company

    if params[:company]
      # get city
      @city = City.where("lower(name) = ? AND region_id = ?", params[:company][:city].downcase, params[:company][:region_id]).first
      if @city.nil?
        @region = Region.find_by_id(params[:company][:region_id])
        @city = @region.cities.create(:name => params[:company][:city]) if @region
      end
      params[:company][:city_id] = @city.id if @city

      if @company.update_attributes(params[:company].except(:city))
        redirect_to company_add3_url(:id => @company.id)
      else
        flash[:error] = @company.errors.values[0][0]
      end
    end

	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 2", "firma-eintragen/schritt-2"
  end
  
  def eintragen3
    @company = Company.find(params[:id])
    authorize! :update, @company

    if params[:company]
      specialties = prepare_specialties(params[:company].delete(:specialties))
      subcategories = prepare_subcategories params[:company].delete(:subcategories)

      if @company.update_attributes(params[:company])
        @company.tags << specialties
        @company.subcategories << subcategories
        @company.save
        redirect_to company_add4_url(:id => @company.id)
      else
        flash[:error] = @company.errors.values[0][0]
      end
    end

	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 3", "firma-eintragen/schritt-3"
  end

  def eintragen4
	  add_breadcrumb "Firma eintragen  - #{t('general.step')} 4", "firma-eintragen/schritt-4"
  end

  private

################ adding company - step 1 ##################################

  def find_or_restore_company_step1
    @company =  if params[:id].present?
                  Company.find(params[:id])
                else
                  Company.new(temp_company)
                end
  end

  def add_company_step1
    unless user_signed_in?
      save_temp_data_to_login
      return
    end

    temp_company_clear
    @company =  params[:id].present? ? Company.find(params[:id]) : Company.new
    company_params = params[:company]
    company_params[:user_id] = current_user.id
    if @company.update_attributes(company_params)
      redirect_to company_add2_url(:id => @company.id)
    else
      flash[:error] = @company.errors.values[0][0]
    end
  end

  def save_temp_data_to_login
      self.temp_company = params[:company]
      session[:user_return_to] = request.url
      flash[:error] = t(:you_need_to_login_to_continue)
  end

  def temp_company
    session[:company] if session[:company].present?
  end

  def temp_company=(value)
    session[:company] = value
  end

  def temp_company_clear
    session[:company] = nil
  end

################ adding company - step 1 end ##################################




  def load_cities
      @cities = City.all
  end



  def add_breadcrumb_to_show_page
    add_breadcrumb_by_region_and_city @company.region_name, @company.city_name
    add_breadcrumb @company.name, nil
  end

  def add_breadcrumb_by_region_and_city(region_name=nil, city_name=nil)
    if region_name.nil? and city_name.nil?
      raise ArgumentError 'region_name and city_name are nil!'
    end

    search_options = {:utf8 => "%E2%9C%93", :q=>"architekten"}
    if region_name
      search_options[:region] = region_name
      add_breadcrumb "Architekten #{region_name}",generate_search_query(search_options)
    end

    if city_name
      search_options[:city] = city_name
      add_breadcrumb "Architekten #{city_name}",generate_search_query(search_options)
    end
  end


  def generate_search_query(search_options)
    "/company?#{CGI.unescape(search_options.to_query)}"
  end

  def switzerland_regions
    Country.find_by_name('Switzerland').regions
  end


  def search_page_titles
    title = I18n.t('company.index.title')
    tag = params[:tag]
    city = params[:city]
    region = params[:region]

    if tag.present?  or city.present? or region.present?

      if city.present?
        title << " #{city}"
        title << ", " if region.present?
      end

      title << " #{region}" if region.present?
      title << " - #{tag}" if tag.present?
    else
      title << " #{I18n.t('switzerland')}"
    end

    title
  end

  def append_meta_tags_search_page
    append_meta_keywords_search_page
    append_meta_tag_description "A description of Company -> Architekten search page"
  end

  def append_meta_keywords_search_page
    fields = params.values_at(:tag, :city, :region).select(&:present?)
    append_meta_tag_keywords(fields.join(", ").concat(".")) unless fields.empty?
  end

  def prepare_specialties str_specialties
    current_specialties = @company.tags
    new_specialties = []
    for_destroy = []
    for_create = []

    unless str_specialties.blank?
      str_specialties.split(",").uniq.each do |name|
        new_specialties << Tag.find_or_create_by_name(name: name)
      end
      new_specialties.uniq! unless new_specialties.empty?
    end

    for_destroy = current_specialties - new_specialties
    for_create = new_specialties - current_specialties

    for_destroy.each do |s|
      scp = Tagging.of_tag(s)
      scp = scp.of_taggable(@company)
      scp.destroy_all
    end
    for_create
  end

  def prepare_subcategories str_subcategories
    current_subcategories = @company.subcategories
    new_subcategories = []
    for_destroy = []
    for_create = []
    unless str_subcategories.blank?
      str_subcategories.split(",").uniq.each do |name|
        new_subcategories << Subcategory.find_by_name(name)
      end
      unless new_subcategories.empty?
        new_subcategories.uniq!
        new_subcategories.compact!
      end
    end
    for_destroy = current_subcategories - new_subcategories
    for_create = new_subcategories - current_subcategories

    for_destroy.each do |s|
      scp = CompanySubcategory.where(subcategory_id: s)
      scp = scp.where(company_id: @company)
      scp.destroy_all
    end
    for_create
  end
end

app/helpers/company_helper.rb
module CompanyHelper
  def company_city_name_or_default(company)
      company.city.present?  ? company.city.name : "(undefined city)"
  end

  def google_points_as_json
   points = Company.sponsors.map { |sponsor| {:latitude => sponsor.latitude, :longitude => sponsor.longitude, :name => sponsor.name, :city_name=> sponsor.city_name, :url=>url_to_company(sponsor) } }
    @companies.each do |company|
     if company.latitude and company.longitude
          points << {:latitude => company.latitude, :longitude => company.longitude, :name => company.name, :city_name=> company.city_name, :url=>url_to_company(company)}
     end
    end
   points = points.to_json if points
   points
  end
end

app/views/company/_add_company_sidebar.html.erb
<div id="main-right-wrapper">
  <h3><%= t(:how_does_it_work) %></h3>
  <h3><%= t(:last_entered) %></h3>
</div>

app/views/company/_company.html.erb
<div class="company-container">
  <div class="thumbnail-container">
    <a href="<%= url_to_company(company) %>">
      <%= render :partial => 'company_cover_image', :locals => {:company => company} %>
    </a>
  </div>
  <div class="company-details-container">
  	<div class="company-name-container">
      	<p class="company-name">
          <%= link_to_company(company) %>
        </p>
      </div>
      <div class="company-rating-container">
        <div class="star readonly" score="<%= company.rating %>"></div>
      </div>
      <!-- <div class="company-rating-container">
 	    	<img width="13" height="13" class="star" alt="Star" src="/assets/yellow-star.png">
 	    	<img width="13" height="13" class="star" alt="Star" src="/assets/yellow-star.png">
 	    	<img width="13" height="13" class="star" alt="Star" src="/assets/yellow-star.png">
 	    	<img width="13" height="13" class="star" alt="Star" src="/assets/yellow-star.png">
 	    	<img width="13" height="13" class="star" alt="Star" src="/assets/gray-star.png">
      </div> -->
  </div>
  <input type="button" class="offerte-btn" value="Offerte Einholen" name="">
  <div class="tab-container" id="tab-container-<%= company.id %>" data-easytabs="true">
    <ul class="etabs">
      <li class="tab active">
        <a href="#tabs1-intro" class="active">Intro</a>
      </li>
      <li class="tab"><a href="#tabs-kontakt-<%= company.id %>">Kontakt</a></li>
      <li class="tab"><a href="#tabs-katalog-<%= company.id %>">Katalog</a></li>
      <li class="tab"><a href="#tabs-abbildungen-<%= company.id %>">Abbildungen</a></li>
      <li class="tab"><a href="#tabs-referenzen-<%= company.id %>">Referenzen</a></li>
      <li class="tab"><a href="#tabs-news-<%= company.id %>">News</a></li>
    </ul>
    <div class="panel-container">
      <div id="tabs-intro-<%= company.id %>" style="display: block;" class="active">
       <p><%= raw company.description %></p>
      </div>
       <div id="tabs-kontakt-<%= company.id %>" style="display: none;">
       <p>
        <%= company.contact_person %>,
        <%= company.email %>,
        <%= company.websites.join(",") %>,
        <%= company.phone_numbers.join(",") %>,
        <%= company.address %>,
        <%= company.postal_code %>
       </p>
      </div>
      <div id="tabs-katalog-<%= company.id %>" style="display: none;">
      <p>die passenden Anbieter fir Ihr Projekt.</p>
      </div>
      <div id="tabs-abbildungen-<%= company.id %>" style="display: none;">
      <p>Anbieter fir Ihr Projekt.</p>
      </div>
      <div id="tabs-referenzen-<%= company.id %>" style="display: none;">
      <p>Finden Sie mit wenigen Mausklicks die passenden</p>
      </div>
      <div id="tabs-news-<%= company.id %>" style="display: none;">
      <p>Finden Sie mit wenigen</p>
      </div>
    </div>
  </div>
  <div class="clr"></div>
  <div class="company-tags-container">
    <% company.tags.each do |t| %>
      <div class="company-tags">
      <%= link_to company_index_url(:region => params[:region], :tag => t.name) do %>
        <%= t.name %>
      <% end %>
      </div>
    <% end %>
  </div>
  <div class="clr"></div>
</div>

app/views/company/_company_cover_image.html.erb
<% size||= '200x140'%>
<% if company.cover_image_uid %>
  <%= image_tag company.cover_image.thumb(size).url %>
<% elsif company.images.length > 0 %>
  <%= image_tag company.images.first.image.thumb(size).url %>
<% else %>
  <%= image_tag 'company-icon.jpg' %>
<% end %>

app/views/company/_subcategories.html.erb
$("#subcategory-section").html()

app/views/company/eintragen.html.erb
<% content_for :title, t(:addcompany) %>

<div id="main-left-wrapper">
	<h2><%= t(:addcompany) %></h2>
  <p><%= t(:add_company_intro).html_safe %></p>
	<br>

  <h2><%= t(:register_your_company) %></h2>

  <%= form_for @company, :url => (@company.id) ? company_add_url(:id => @company.id) : company_add_url,
               :html => {:name => 'company_add_form', :id => 'company_add_form',
                         :class => 'remember-cookie'} do |f| %>

    <div class="clearfix">
      <label class="form-label" for="company_name"><%= t(:companyname) %></label>
      <div class="control-group">
        <%= f.text_field :name, {:class => 'form-input tooltippable', :title => t('hints.official_company_name'),
                                 'original-name' => @company.name,:data => {:placement=>'right', :trigger => "focus"}, :class => "add_tooltip"} %>
      </div>
    </div>

    <div class="clearfix">
      <label class="form-label" for="company_region_id"><%= t(:your_region) %></label>
      <div class="control-group">
        <select id="company_region_id" name="company[region_id]" class="tooltippable add_tooltip" title="<%= t('hints.please_select_your_region') %>" data-placement="right">
          <option value="0"><%= t(:selectregion) %></option>
          <% @regions.each do |region| %>
            <option value="<%= region.id %>" <%= (@company.region_id == region.id) ? 'selected="selected"' : '' %>>
              <%= region.name %>
            </option>
          <% end %>
        </select>
      </div>
    </div>

    <div><%= submit_tag t(:nextstep), :class => 'btn' %></div>

  <% end %>
</div>

<div id="main-right-wrapper">
  <h3><%= t(:how_does_it_work) %></h3>
  <ul>
    <li>
      <a href="#">Einmal ausfüllen</a>
    </li>
    <li>
      <a href="#">Schnell 3 Offerten erhalten</a>
    </li>
    <li>
      <a href="#">Kostenlos</a>
    </li>
    <li>
      <a href="#">Unverbindlich</a>
    </li>
    <li>
      <a href="#">Von den besten Architekten in Ihrer Umgebung</a>
    </li>
  </ul>
   
  <div class="clr"><br><br><br></div>

  <%= render "layouts/latest_news"%>

  <div class="clr"><br><br><br></div>  

  <%= render :partial => 'add_company_sidebar' %>

</div>
<div class="clr"></div>

app/views/company/eintragen4.html.erb
<% content_for :title, t(:addcompany) %>


<div id="main-left-wrapper">

	<h2><%= t(:addcompany) %> - <%= t('general.step') %> 4</h2>

  <%= t('add_company_page4.intro').html_safe %>
	

	<br>

  <h2><%= t('add_company_page4.your_membership') %></h2>

  <div class="membership-selection-container">
    <div class="membership-selection">
      <div class="title-section">
        <div class="title">BASIS</div>
        <div class="subtitle">MITGLIEDSCHAFT</div>
      </div>
      <div class="price-section">
        KOSTENLOS
      </div>
      <div class="content-section">
        <ul>
          <li>400GB Monthly Bandwidth</li>
          <li>25GB Web Storage</li>
          <li>24/7 Customer Support</li>
          <li>2 Free Domain Names</li>
          <li>$20 Google Adwords</li>
          <li>100MB Space/Email Account</li>
        </ul>
        <a href="<%= company_add_finish_url %>">ABSCHLIESSEN</a>
      </div>
    </div>
  </div>

  <div class="membership-selection-container">
    <div class="membership-selection">
      <div class="title-section">
        <div class="title">PREMIUM</div>
        <div class="subtitle">MITGLIEDSCHAFT</div>
        <div class="extra">
          Am häufigsten gewählt<br/>
          Ideal für die meisten Firmen
        </div>
      </div>
      <div class="price-section">
        49.95 CHF pro Monat
      </div>
      <div class="content-section">
        <ul>
          <li>500GB Monthly Bandwidth</li>
          <li>50GB Web Storage</li>
          <li>24/7 Customer Support</li>
          <li>5 Free Domain Names</li>
          <li>$30 Google Adwords</li>
          <li>125MB Space/Email Account</li>
          <li>40 Email Accounts</li>
        </ul>
        <a href="<%= company_payment_url %>">ABSCHLIESSEN</a>
      </div>
    </div>
  </div>

  <div class="membership-selection-container">
    <div class="membership-selection">
      <div class="title-section">
        <div class="title">ELITE</div>
        <div class="subtitle">MITGLIEDSCHAFT</div>
      </div>
      <div class="price-section">
        299.95 CHF pro Monat
      </div>
      <div class="content-section">
        <ul>
          <li>Nur 10 Untemehmen</li>
          <li>100% kostenlose Offerten</li>
          <li>24/7 Customer Support</li>
          <li>5 Free Domain Names</li>
          <li>$50 Google Adwords</li>
          <li>150MB Space/Email Account</li>
          <li>Unlimited Email Accounts</li>
        </ul>
        <div style="text-align: center;">
          <a href="<%= company_add_finish_url %>">ABSCHLIESSEN</a>
        </div>
      </div>
    </div>
  </div>

  <!--
  <center>
    <a href="<%= company_add_finish_url %>"><img src="/images/pricing-table.png" border=0></a>
  </center>
  -->
</div>

<%= render :partial => 'add_company_sidebar' %>
<div class="clr"></div>

app/views/company/payment.html.erb
<% content_for :title, t(:payment) %>


<div id="main-left-wrapper">

	<h2>Premium Mitgliedschaft - Abrechnung</h2>

	<p>
	Im folgenden wählen Sie bitte eine Abrechnungsmethode für die Zahlung der Mitgliedsbeiträge:	
	</p>

	

</div>

<%= render :partial => 'add_company_sidebar' %>
<div class="clr"></div>

app/views/company/show.html.erb
<% content_for :head do %>
  <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('#new_review').submit(function(event) {
        event.preventDefault();
        $(this).ajaxSubmit({
          success: function(data) {
            if (data['success']) {
              window.location = '<%= request.fullpath %>';
            }
          }
        })
      });
    });
  </script>
<% end %>

<% if can? :update, @company %>
  <div style="clear: both; padding: 10px 0;">
    <%= link_to 'Edit', edit_company_url(@company) %>
  </div>
<% end %>

<div id="main-left-wrapper" >
  <h2><%= @company.name %></h2>
  <div class="company-info-section bottom-block-wrapper">
    <div class="company-header clearfix">
      <div class="company-name" style="float: left; margin-right: 10px;"><%= company_city_name_or_default(@company) %></div>
      <div class="company-rating star readonly" style="float: left;" score="<%= @company.rating %>"></div>
    </div>
    <div class="company-thumbnail">
      <%= render :partial => 'company_cover_image', :locals => {:company => @company} %>
    </div>
    <div class="company-detail">
      <%= @company.address %><br />
      <% if @company.phone_numbers %>
        <% @company.phone_numbers.each do |phone_number| %>
          <%= phone_number %><br />
        <% end %>
      <% end %>
      <a href="mailto:<%= @company.email %>"><%= @company.email %></a><br />
      <% if @company.websites %>
        <% @company.websites.each do |website| %>
          <a href="<%= website %>"><%= website %></a><br />
        <% end %>
      <% end %>
    </div>
    <div style="clear: both"></div>
    <div class="company-description">
      <p><%= raw @company.description %></p>
    </div>
  </div>

  <div class="company-images-section bottom-block-wrapper">
    <div class="title"><%= t('company_show_page.gallery') %></div>
    <% @company.images[0..2].each do |image| %>
      <%= image_tag image.image.thumb('200x140').url if image.image_uid %>
    <% end %>
  </div>
  <div class="company-reviews-section bottom-block-wrapper">
    <div class="title"><%= t('company_show_page.review') %></div>

    <div id="write_review" class="write-review">
      <%= form_for [@company, Review.new] do |f| %>
        <table>
          <tr>
            <td><%= f.label :rating %></td>
            <td>
              <div class="star" score-name="review[rating]"></div>
            </td>
          </tr>
          <tr>
            <td><%= f.label :content, 'Review' %></td>
            <td><%= f.text_area :content, :rows => 5 %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit t(:writereview) %></td>
          </tr>
        </table>
      <% end %>
    </div>

    <% @company.reviews.latest[0..2].each do |review| %>
      <div class="review">
        <div class="review-user"><%= review.user.name %></div>
        <div class="review-rating"><div class="star readonly" score="<%= review.rating %>"></div></div>
        <div class="review-content"><%= review.content %></div>
        <div class="review-time"><%= time_ago_in_words(review.created_at) %></div>
      </div>
    <% end %>
  </div>
  <div class="company-tags-section bottom-block-wrapper">
    <div class="title"><%= t('company_show_page.specialty') %></div>
    <% @company.tags.each do |t| %>
      <%= link_to company_index_url(:region => @company.region.name, :tag => t.name), :class=>"tag" do %>
        <span class="tag"><%= t.name %></span>
      <% end %>
    <% end %>
  </div>
  <div class="company-additional-info-section bottom-block-wrapper">
    <div class="title"><%= t('company_show_page.additional_info') %></div>
    <p>
    </p>
  </div>
</div>

<div id="main-right-wrapper">
  <div class="company-quote-section side-bar">
    <%= link_to new_offer_url, :class=>"btn btn-success", :id=>"offerten" do %>
      <table height="75">
        <tr>
          <td style="min-width:85px;max-width:85px;"><%= "Offerte Anfordern!" %></td>
          <td style="min-width:155px;"><span class="offerte-compname"><%= @company.name %></span></td>
        </tr>
      </table>
    <% end %>
  </div>
  <div class="clr"><br><br><br></div>
  <% if @company.latitude and @company.longitude %>
    <div class="company-map-section side-bar">
      <h3 class="title"><%= t('company_show_page.location_of') %> <%= company_city_name_or_default(@company) %></h3>
      <div class="map_canvas readonly" style="width: 100%; height: 200px;"
           latitude="<%= @company.latitude %>" longitude="<%= @company.longitude %>" zoom="13"></div>
    </div>
  <% end %>
  <div class="clr"><br><br><br></div>
  <div class="company-others-section side-bar min200height">
    <h3 class="title"><%= t('company_show_page.other_architects') %> in <%= @company.region_name %></h3>
    <ul>
      <% @company.other_companies_from_region.each do |c| %>
        <li>
          <%= link_to_company(c) %>
          <div class="star readonly" score="<%= c.rating %>"></div>
          <div class="image">
            <a href="<%= url_to_company(c) %>">
              <%= render :partial => 'company_cover_image', :locals => {:company => c, :size => '100x80'} %>
            </a>
        </div>
        </li>
      <% end %>
    </ul>
  </div>
  
</div>
<div class="clr"></div>